"""Add DateTime

Revision ID: 701b8aaed618
Revises: 8fb6b76baee7
Create Date: 2024-12-04 12:55:38.078260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701b8aaed618'
down_revision = '8fb6b76baee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
